SELECT	* FROM	fabryka_samochodow.dbo.dzialy
SELECT	* FROM	fabryka_samochodow.dbo.stanowiska
SELECT	* FROM	fabryka_samochodow.dbo.pracownicy
SELECT	* FROM	fabryka_samochodow.dbo.silniki
SELECT	* FROM	fabryka_samochodow.dbo.egzemplarze
SELECT	* FROM	fabryka_samochodow.dbo.egzemplarze_zamowienia
SELECT	* FROM	fabryka_samochodow.dbo.zamowienia
SELECT	* FROM	fabryka_samochodow.dbo.klienci
SELECT	* FROM	fabryka_samochodow.dbo.samochody
SELECT	* FROM	fabryka_samochodow.dbo.dzialy_samochody